version: "3"
services:
  mlflow:
    build:
      context: .
    command:
      - bash
      - -c
      - "mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./run_env/data:/mlflow
